import type { Metadata } from "next";
import "./global.css";
import Navigation from "./components/nav/nav";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Магазин Квартир",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <header>
          <Navigation />
        </header>
        <main>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
